[package]
name = "insert_many"
version = "0.1.0"
authors = ["Robert Habermeier <rphmeier@gmail.com>"]

[dependencies]
smallvec = { version = "0.2.0", optional = true }

[features]
default = ["smallvec"]